backend:
  name: github
  repo: ahmed025/SidiT
  branch: main
  base_url: https://sititech.up.railway.app
  auth_endpoint: auth

media_folder: "assets/img"
public_folder: "/assets/img"

media_library:
  name: default

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "hero_title", label: "Hero Title", widget: "string" }
          - { name: "hero_description", label: "Hero Description", widget: "text" }
          - { name: "hero_button_text", label: "Hero Button Text", widget: "string" }
