backend:
  name: github
  repo: ahmed025/SidiT
  branch: main
  base_url: https://siditechweb.vercel.app
  auth_endpoint: /api/auth
 

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
