backend:
  name: github
  repo: ahmed025/SidiT       # ✅ Make sure this repo is public or you’ve authenticated properly
  branch: main
  base_url: sititech.up.railway.app
  auth_endpoint: auth         # ❗️ Fix: should be just 'auth', not 'api/auth'

media_folder: "assets/img"    # ✅ Path inside the repo where uploads go (frontend-side)

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "hero_title", label: "Hero Title", widget: "string" }
          - { name: "hero_description", label: "Hero Description", widget: "text" }
          - { name: "hero_button_text", label: "Hero Button Text", widget: "string" }

  - name: "globals"
    label: "Globals"
    files:
      - name: "navigation"
        label: "Navigation"
        file: "content/globals/navigation.json"
        fields:
          - name: "menu_items"
            label: "Menu Items"
            widget: "list"
            fields:
              - { name: "label", label: "Label", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
