backend:
  name: github
  repo: ahmed025/SidiT        # Your GitHub repo
  branch: main
  base_url: https://sititech.up.railway.app
  auth_endpoint: auth         # Custom auth endpoint (must be working)

media_folder: "assets/img"    # Where uploaded media files go in the repo
public_folder: "/assets/img"  # How the CMS references them in URLs

media_library:
  name: uploadcare            # Optional: you can remove this if you're not using Uploadcare
  config: {}

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "hero_title", label: "Hero Title", widget: "string" }
          - { name: "hero_description", label: "Hero Description", widget: "text" }
          - { name: "hero_button_text", label: "Hero Button Text", widget: "string" }

  - name: "globals"
    label: "Globals"
    files:
      - name: "navigation"
        label: "Navigation"
        file: "content/globals/navigation.json"
        fields:
          - name: "menu_items"
            label: "Menu Items"
            widget: "list"
            fields:
              - { name: "label", label: "Label", widget: "string" }
              - { name: "url", label: "URL", widget: "string" }
